messages:
  pressSpace: "Press and hold space to speak"
  loadingModel: "Loading..."
  noAudioInput: "Error: No sound input!"

whisperRecognition:
  modelPath: "whisper/base.pt"
  lang: "fr"

ollama:
  url: "http://localhost:11434/api/generate"
  model: "mistral"

conversation:
  greeting: "Bonjour mon altesse, comment je peux t'aider?"

